apps/contractor/urls.py
"""
URLs CONTRACTORS
"""
from django.contrib.auth.decorators import login_required

from django.conf.urls import url
from apps.contractor.views import index, ContractorCreate, ContractorList, ContractorUpdate, ContractorDelete, ContractorDetail, \
    EmployeeFieldList, EmployeeFieldCreate, EmployeeFieldUpdate, \
    ContractorEmployeeFieldCreate, ContractorEmployeeFieldList, ContractorEmployeeFieldAllList, ContractorEmployeeFieldUpdate, ContractorEmployeeFieldAllUpdate,\
    EmployeeFieldProfile,get_data, ContractorChartData


urlpatterns = [
    url(r'^$', index, name='index'),

    url(r'^(?P<pk>\d+)/create/$', \
        login_required(ContractorCreate.as_view()), name='contractor_create'),

    url(r'^(?P<pk>\d+)/list/$', \
        login_required(ContractorList.as_view()), name='contractor_list'),

    url(r'^(?P<companies_id>\d+)/update/(?P<pk>\d+)/$', \
        login_required(ContractorUpdate.as_view()), name='contractor_update'),

    url(r'^(?P<companies_id>\d+)/delete/(?P<pk>\d+)/$', \
        login_required(ContractorDelete.as_view()), name='contractor_delete'),

    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/detail/$', login_required(ContractorDetail.as_view()), name='contractor_detail'),

    # URLs CONTRACTOR EMPLOYEE FIELD
    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/contractor_employee_field_list/$', \
        login_required(ContractorEmployeeFieldList.as_view()), name='contractor_employee_field_list'),

    # all employees
    url(r'^(?P<pk>\d+)/contractor_employee_field_all_list/$', \
        login_required(ContractorEmployeeFieldAllList.as_view()), name='contractor_employee_field_all_list'),

    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/contractor_employee_field_create/(?P<pk>\d+)/$', \
        login_required(ContractorEmployeeFieldCreate.as_view()), name='contractor_employee_field_create'),

    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/contractor_employee_field_update/(?P<pk>\d+)/$', \
        login_required(ContractorEmployeeFieldUpdate.as_view()), name='contractor_employee_field_update'),

    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/contractor_employee_field_all_update/(?P<pk>\d+)/$', \
        login_required(ContractorEmployeeFieldAllUpdate.as_view()), name='contractor_employee_field_all_update'),


    # URLs: EMPLOYEE FIELDs
    url(r'^(?P<companies_id>\d+)/employee_field_create/(?P<pk>\d+)/$', login_required(EmployeeFieldCreate.as_view()), name='employee_field_create'),
    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/employee_field_update/$', login_required(EmployeeFieldUpdate.as_view()),
        name='employee_field_update'),
    url(r'^(?P<pk>\d+)/employee_field_list/$', login_required(EmployeeFieldList.as_view()), name='employee_field_list'),

    # Profile
    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/(?P<pk>\d+)/employee_field_profile/$', login_required(EmployeeFieldProfile.as_view()),
        name='contractor_employee_field_profile'),

    # DATA Graph
    url(r'^(?P<pk>\d+)/api/data/$', login_required(get_data), name='api-data'),
    url(r'^(?P<pk>\d+)/api/chart/data/$', login_required(ContractorChartData.as_view())),
    ###################

]

apps/employee/urls.py
"""
URLs Employees
"""
from django.contrib.auth.decorators import login_required

from django.conf.urls import url
from apps.employee.views import EmployeeCreate,EmployeeUpdate, EmployeeList, EmployeeDelete, \
    EmployeeListCard, EmployeeProfile

urlpatterns = [
    url(r'^(?P<pk>\d+)/create/$', login_required(EmployeeCreate.as_view()), name='employee_create'),
    url(r'^(?P<pk>\d+)/list/$', login_required(EmployeeList.as_view()), name='employee_list'),
    url(r'^(?P<companies_id>\d+)/update/(?P<pk>\d+)/$', login_required(EmployeeUpdate.as_view()), name='employee_update'),
    url(r'^(?P<companies_id>\d+)/delete/(?P<pk>\d+)/$', login_required(EmployeeDelete.as_view()), name='employee_delete'),

    # Others Actions
    url(r'^(?P<companies_id>\d+)/profile/(?P<pk>\d+)/$', login_required(EmployeeProfile.as_view()), name='employee_profile'),
    url(r'^(?P<companies_id>\d+)/card/(?P<letter>.+)/$', login_required(EmployeeListCard.as_view()), name='employee_list_card'),
]

samson_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from django.conf import settings
from django.conf.urls.static import static
from django.template.backends import django

from apps.company.views import index, CompanyDashboard, RedirectDashboard, CompanyPending

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^404/$', login, {'template_name': '404.html'}, name='error_404'),
                  url(r'^company/', include(('apps.company.urls', 'company'), namespace='company')),
                  url(r'^company_dashboard/',
                      include(('apps.user_profile.urls', 'user_profile'), namespace="company_dashboard")),

                  url(r'^project/', include(('apps.project.urls', 'project'), namespace="project")),

                  url(r'^employee/', include(('apps.employee.urls', 'employee'), namespace="employee")),
                  url(r'^contractor/', include(('apps.contractor.urls','contractor'), namespace="contractor")),
                  url(r'^general_contractor/', include(('apps.general_contractor.urls', 'general_contractor'), namespace="general_contractor")),

                  url(r'^user_profile/', include(('apps.user_profile.urls', 'user_profile'), namespace="user_profile")),

                  url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
                  url(r'^$', login, {'template_name': 'index.html'}, name='login'),
                  # url(r'^dashboard/', DashBoard.as_view(), name='dashboard'),
                  url(r'^logout/', logout_then_login, name='logout'),
                  url(r'^redirect_dashboard/', RedirectDashboard, name='redirect_dashboard'),
                  url(r'^dashboard/', CompanyDashboard, name='company_dashboard'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Necesario por error de Page no found en directorio Media

apps/contractor/views.py
from django.shortcuts import render, redirect

from apps.contractor.forms import ContractorForm, EmployeeFieldForm, ContractorEmployeeFieldForm
from apps.contractor.models import Contractor, EmployeeField, ContractorEmployeeField
from apps.project.models import ProjectContractor, DailyProduce, ProjectContractorEmployeeField
from apps.company.models import Company

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.db.models import F, Q, Sum, Avg, Max, Min, Case, When

# Import Graph
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'base/index.html')

# Create your views here.
# ==================================
# CONTRACTOR CRUD
# ==================================
class ContractorCreate(CreateView):
    model = Contractor
    form_class = ContractorForm
    template_name = 'apps/contractor/contractor_form.html'
    success_url = reverse_lazy('contractor:contractor_list')

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        return super(ContractorCreate, self).form_valid(form)

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(ContractorCreate, self).get_initial()
        companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
        initial.update(
            {
                'companies_id': companies_id['id'],
                'companies': companies_id['id'],
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(ContractorCreate, self).get_form_kwargs()
        companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
            })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('contractor:contractor_list', kwargs={'pk': self.kwargs['pk']})
        else:
            return reverse_lazy('contractor:contractor_list', args=(self.object.id,))


class ContractorList(ListView):
    model = Contractor
    template_name = 'apps/contractor/contractor_list.html'

    # Pasar parametros a la plantilla usando context
    def get_context_data(self, **kwargs):
        context = super(ContractorList, self).get_context_data(**kwargs)

        context['contractorList'] = Contractor.objects.all().filter(companies_id=self.kwargs['pk'])

        return context


class ContractorUpdate(UpdateView):
    model = Contractor
    form_class = ContractorForm
    template_name = 'apps/contractor/contractor_form.html'
    success_url = reverse_lazy('contractor:contractor_list')

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(ContractorUpdate, self).get_initial()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        initial.update(
            {
                'companies_id': companies_id['id'],
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(ContractorUpdate, self).get_form_kwargs()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
            })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('contractor:contractor_list', kwargs={'pk': self.kwargs['companies_id']})
        else:
            return reverse_lazy('contractor:contractor_list', args=(self.object.id,))


class ContractorDelete(DeleteView):
    model = Contractor
    template_name = 'apps/contractor/contractor_delete.html'
    success_url = reverse_lazy('contractor:contractor_list')


    def get_context_data(self, **kwargs):

        context = super(ContractorDelete, self).get_context_data(**kwargs)
        a = ''
        b  = ''
        a = ProjectContractor.objects.filter(contractors_id=self.kwargs['pk']).count()
        b = ContractorEmployeeField.objects.filter(contractors_id=self.kwargs['pk']).count()

        if a > 0:
            context['DeleteRegisterExist'] = a

        if b > 0:
            context['DeleteRegisterExist'] = b

        context['DeleteRegister'] = Contractor.objects.get(companies_id=self.kwargs['companies_id'], pk=self.kwargs['pk'])

        return context

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('contractor:contractor_list', kwargs={'pk': self.kwargs['companies_id']})
        else:
            return reverse_lazy('contractor:contractor_list', args=(self.object.id,))


# ###################
# CONTRACTOR DETAIL #
# ###################

class ContractorDetail(DetailView):
    model = Contractor
    template_name = 'apps/contractor/contractor_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ContractorDetail, self).get_context_data(**kwargs)

        ########################################
        # Employee List Assigned to Contractor #
        ########################################
        contractor_employee_field_list = ContractorEmployeeField.objects.select_related('contractors'). \
            all().filter(contractors_id=self.kwargs['pk'])

        context['ContractorEmployeeFieldList'] = contractor_employee_field_list

        ########################################
        # Employee List Assigned to Contractor #
        ########################################
        project_contractor_list = ProjectContractor.objects.select_related('contractors'). \
            all().filter(contractors_id=self.kwargs['pk'])

        context['ProjectContractorList'] = project_contractor_list

        total_projects = 0
        total_man_days = 0
        total_production_exp = 0
        total_produccion_exe = 0
        total_employees = 0
        total_hours = 0
        total_cost_man_days_spend = 0

        # { MAN DAYS CALCULATOR
        total_projects = ProjectContractor.objects.all().filter(contractors_id=self.kwargs['pk']).count()
        total_employees_field = ContractorEmployeeField.objects.all().filter(contractors_id=self.kwargs['pk']).count()

        contractor_cost_hours = DailyProduce.objects. \
            values('project_contractor_employees_field__project_contractors__contractors__companies__name'). \
            filter(project_contractor_employees_field__project_contractors__contractors__id=self.kwargs['pk']). \
            annotate(
            cost=Sum(
                Case(
                    When(project_manday_schedules__projects__is_wage_scale=False,
                         then=F('work_hours') * F('project_manday_schedules__regular_cost')
                         ),
                    When(project_manday_schedules__projects__is_wage_scale=True,
                         then=F('work_hours') * F('project_manday_schedules__wage_cost')
                         )
                )
            ),
            cost_md=Sum(
                Case(
                    When(project_manday_schedules__projects__is_wage_scale=False,
                         then=F('work_hours') * F('project_manday_schedules__regular_cost')
                         ),
                    When(project_manday_schedules__projects__is_wage_scale=True,
                         then=F('work_hours') * F('project_manday_schedules__wage_cost')
                         )
                )
            ),
            hours=Sum('work_hours')
        )

        if contractor_cost_hours.count() > 0:
            if contractor_cost_hours[0]['cost'] is not None and contractor_cost_hours[0]['hours'] is not None:
                total_cost_man_days_spend = contractor_cost_hours[0]['cost']
                total_hours = contractor_cost_hours[0]['hours'] + 0

        data = ({
            'total_projects': total_projects,
            'total_man_days': total_hours / 8,
            'total_cost_man_days_spend': total_cost_man_days_spend,
            'total_produccion_exe': total_produccion_exe,
            'total_employees_field': total_employees_field
        })
        context['ContractorDetail'] = data

        return context

#############################
# CONTRACTOR EMPLOYEE FIELD #
#############################

class ContractorEmployeeFieldCreate(CreateView):
    model = ContractorEmployeeField
    form_class = ContractorEmployeeFieldForm
    template_name = 'apps/contractor/contractor_employee_field/contractor_employee_field_form.html'

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        form.save(commit=False)  # Para obtener el ID
        EmployeeField.objects.filter(id=form.instance.employees_field_id).update(is_assigned=True)

        form.save()  # Guardamos el codigo

        return super(ContractorEmployeeFieldCreate, self).form_valid(form)

    def get_initial(self):
        initial = super(ContractorEmployeeFieldCreate, self).get_initial()

        initial.update(
            {
                'companies':self.kwargs['companies_id'],
                'contractors': self.kwargs['contractor_id'],
                'contractor_id': self.kwargs['contractor_id'],
                'employees_field': self.kwargs['pk']
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(ContractorEmployeeFieldCreate, self).get_form_kwargs()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
                'contractor_id': self.kwargs['contractor_id'],
                'employees_field_id': self.kwargs['pk'],
            })

samson_project/templates/apps/contractor/contractor_employee_field/contractor_employee_field_all_list.html
{% extends "base/base_site.html" %}
<title>SAMSON Project Management and Comunication - SPMC | {% block title %} Contractor Employees List {% endblock %}</title>

{% block stylesheets %}
    {{ block.super }}
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    {#                    <h3>Employees Field List</h3>#}
                </div>


                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">

                            {#                            <button class="btn btn-default" type="button">Go!</button>#}
                            <span class="input-group-btn">
                             </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <div class="x_title">
                                <h3 align="center" class="green"><strong>List of Employees Field </strong> | Ordered by Contractor.</h3>
                            </div>
                        </div>

                        <div class="x_content">
                            <table id="datatable-buttons" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Avatar</th>
                                    <th>Employee CODE</th>
                                    <th>Employee Field Name</th>
                                    <th>Contacts</th>
                                    <th>Address</th>
                                    <th>Contractor</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if EmployeeFieldAllList %}
                                    {% for employee_field_all_list in EmployeeFieldAllList %}
                                        <tr>
                                            <th width="5%">
                                                {% if employee_field_all_list.employees_field.avatar %}
                                                    <img class="img-responsive avatar-view" src="/media/{{ employee_field_all_list.employees_field.avatar }}" alt="Avatar" title="Change the avatar">
                                                {% else %}
                                                    <img class="img-responsive avatar-view" src="/static/images/user-flat.png" alt="Avatar" title="Change the avatar">
                                                {% endif %}

                                            </th>

                                            <th width="5%">
                                                <strong><span class="badge bar-success">{{ employee_field_all_list.employees_field.employee_field_code }}</span></strong>
                                            </th>
                                            <td>
                                                <strong>{{ employee_field_all_list.employees_field.first_name }} {{ employee_field_all_list.employees_field.last_name }}</strong>
                                                </br>
                                                <span class="blue">{{ employee_field_all_list.employees_field.category_employees_field }}</span>
                                            </td>

                                            <td>
                                                {{ employee_field_all_list.employees_field.cell_phone_number }} </br>
                                                <span class="blue">{{ employee_field_all_list.employees_field.email }}</span>
                                            </td>

                                            <td>{{ employee_field_all_list.employees_field.street_address }}, </br>
                                                <span class="green">
                                                    {{ employee_field_all_list.employees_field.city_address }}, {{ employee_field_all_list.employees_field.state_address }}
                                                </span>
                                            </td>
                                            <th>
                                                {{ employee_field_all_list.contractors.name }} </br>
                                                <span class="green">
                                                    {{ employee_field_all_list.contractors.phone_number }}
                                                </span>
                                            </th>
                                            <td>
                                                {% comment %}                                                <a href="{% url 'contractor:contractor_employee_field_profile' employee_field_all_list.contractors.id employee_field_all_list.employees_field.id %}" class="btn btn-info btn-xs"><i class="fa fa-plus-circle"></i> Profile </a>{% endcomment %}
                                                {%  if user.userprofile.role is 1  %}
                                                    <a href="{% url 'contractor:employee_field_update' user.userprofile.companies.id employee_field_all_list.employees_field.id  %}" class="btn .btn-transparent btn-xs"><i class="fa fa-pencil fa-lg"></i> </a>
                                                    <a href="{% url 'contractor:contractor_employee_field_all_update' user.userprofile.companies.id employee_field_all_list.contractors.id employee_field_all_list.id  %}" class="btn .btn-transparent btn-xs"><i class="fa fa-link fa-lg"></i> </a>
                                                {% endif %}
                                                <a href="{% url 'contractor:contractor_employee_field_profile' user.userprofile.companies.id employee_field_all_list.contractors.id employee_field_all_list.employees_field.id  %}" class="btn .btn-transparent btn-xs"><i class="fa fa-gear fa-lg"></i> </a>

                                            </td>

                                        </tr>
                                    {% endfor %}

                                {% else %}
                                    <h4 class="red">We have not yet found information in our database of the selected option.</h4>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>

{% endblock javascripts %}

samson_project/templates/apps/contractor/contractor_employee_field/employee_field_list_card.html
{% extends "base/base_site.html" %}
<title>SAMSON Project Management and Comunication - SPMC | {% block title %} Contats Lists {% endblock %}</title>
{% block stylesheets %}
    {{ block.super }}
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Contacts: Dynamic Contracting Inc.</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
{#                <button class="btn btn-default" type="button">Go!</button>#}
              </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12">
                    <div class="x_panel">
                        <div class="x_content">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                                    <ul class="pagination pagination-split">
                                        <li><a href="{%  url 'employee:employee_list_card' 'All' user.username %}">All</a></li>

                                    </ul>
                                </div>

                                <div class="clearfix"></div>
                                {% if object_list %}
                                    {% for employee in object_list %}

                                        <div class="col-md-4 col-sm-4 col-xs-12 profile_details">

                                            <div class="well profile_view">
                                                <div class="col-sm-12">
                                                    <h3 class="brief"><i>{{ employee.company }}</i></h3>
                                                    <div class="left col-xs-7">
                                                        <h3>{{ employee.first_name }} {{ employee.last_name }}</h3>
{#                                                        <p><strong>About: </strong> Web Designer / UX / Graphic Artist / Coffee Lover </p>#}
                                                        <ul class="list-unstyled">
                                                            <li><i class="fa fa-building"></i> Address: {{ employee.street_address }} {{ employee.city_address }} {{ employee.state_address }}</li>
                                                            <li><i class="fa fa-phone"></i> Phone #: {{ employee.cell_phone_number }}</li>
                                                            <li><i class="fa fa-envelope"></i> Email: {{ employee.email }}</li>
                                                        </ul>
                                                    </div>
                                                    <div class="right col-xs-5 text-center">
                                                        {% if employee.avatar %}
                                                            <img src="/{{ employee.avatar }}" alt="" class="img-circle img-responsive">
                                                        {% else %}
                                                            <img src="/static/images/user2.png" alt="" class="img-circle img-responsive">
                                                        {% endif %}
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 bottom text-center">

                                                    <div class="col-xs-12 col-sm-6 emphasis">
                                                        <button type="button" class="btn btn-success btn-xs">
                                                            <i class="fa fa-user"></i>
                                                            <i class="fa fa-comments-o"></i>
                                                        </button>

                                                            <a type="button" class="btn .btn-transparent btn-xs" href="{% url 'employee:employee_profile' employee.id %}">
                                                                <i class="fa fa-user"> </i> View Profile
                                                            </a>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}
    {{ block.super }}
{% endblock javascripts %}