apps/company/urls.py
"""
URLs Company
"""
from django.contrib.auth.decorators import login_required

from django.conf.urls import url
from apps.company.views import index, CompanyCreate, CompanyList, CompanyUpdate,  \
    CategoryProjectCreate, CategoryProjectList, CategoryProjectDelete, CategoryProjectUpdate, \
    CategoryEmployeeCreate, CategoryEmployeeList, CategoryEmployeeDelete, CategoryEmployeeUpdate, \
    CategoryCostCodeCreate, CategoryCostCodeList, CategoryCostCodeDelete, CategoryCostCodeUpdate,\
    CostCodeCreate, CostCodeList, CostCodeDelete, CostCodeUpdate, \
    CategoryEmployeeFieldCreate, CategoryEmployeeFieldList, CategoryEmployeeFieldDelete, CategoryEmployeeFieldUpdate, CompanyChartData, get_data, CompanyDashboard, CompanyPending

urlpatterns = [
    url(r'^$', index, name='index'),
    # URLs: Company
    url(r'^create$', login_required(CompanyCreate.as_view()), name='company_create'),
    url(r'^list$', login_required(CompanyList.as_view()), name='company_list'),
    url(r'^update/(?P<pk>\d+)/$', login_required(CompanyUpdate.as_view()), name='company_update'),
    #url(r'^delete/(?P<pk>\d+)/$', login_required(CompanyDelete.as_view()), name='company_delete'),


    # URLs: Category Project
    url(r'^(?P<pk>\d+)/cp_create/$', login_required(CategoryProjectCreate.as_view()), name='category_project_create'),
    url(r'^(?P<pk>\d+)/cp_list/$', login_required(CategoryProjectList.as_view()), name='category_project_list'),
    url(r'^(?P<companies_id>\d+)/cp_update/(?P<pk>\d+)/$', login_required(CategoryProjectUpdate.as_view()), name='category_project_update'),
    url(r'^(?P<companies_id>\d+)/cp_delete/(?P<pk>\d+)/$', login_required(CategoryProjectDelete.as_view()), name='category_project_delete'),


    # URLs: Category Employee
    url(r'^(?P<pk>\d+)/ce_create/$', login_required(CategoryEmployeeCreate.as_view()), name='category_employee_create'),
    url(r'^(?P<pk>\d+)/ce_list/$', login_required(CategoryEmployeeList.as_view()), name='category_employee_list'),
    url(r'^(?P<companies_id>\d+)/ce_update/(?P<pk>\d+)/$', login_required(CategoryEmployeeUpdate.as_view()), name='category_employee_update'),
    url(r'^(?P<companies_id>\d+)/ce_delete/(?P<pk>\d+)/$', login_required(CategoryEmployeeDelete.as_view()), name='category_employee_delete'),


    # URLs: Category Cost code
    url(r'^(?P<pk>\d+)/ccc_create/$', login_required(CategoryCostCodeCreate.as_view()), name='category_cost_code_create'),
    url(r'^(?P<pk>\d+)/ccc_list/$', login_required(CategoryCostCodeList.as_view()), name='category_cost_code_list'),
    url(r'^(?P<companies_id>\d+)/ccc_update/(?P<pk>\d+)/$', login_required(CategoryCostCodeUpdate.as_view()), name='category_cost_code_update'),
    url(r'^(?P<companies_id>\d+)/ccc_delete/(?P<pk>\d+)/$', login_required(CategoryCostCodeDelete.as_view()), name='category_cost_code_delete'),


    # URLs: Cost code
    url(r'^(?P<pk>\d+)/cc_create/$', login_required(CostCodeCreate.as_view()), name='cost_code_create'),
    url(r'^(?P<pk>\d+)/cc_list/$', login_required(CostCodeList.as_view()), name='cost_code_list'),
    url(r'^(?P<companies_id>\d+)/cc_update/(?P<pk>\d+)/$', login_required(CostCodeUpdate.as_view()), name='cost_code_update'),
    url(r'^(?P<companies_id>\d+)/cc_delete/(?P<pk>\d+)/$', login_required(CostCodeDelete.as_view()), name='cost_code_delete'),


    # URLs: Category Employee Field
    url(r'^(?P<pk>\d+)/cef_create/$', login_required(CategoryEmployeeFieldCreate.as_view()), name='category_employee_field_create'),
    url(r'^(?P<pk>\d+)/cef_list/$', login_required(CategoryEmployeeFieldList.as_view()), name='category_employee_field_list'),
    url(r'^(?P<companies_id>\d+)/cef_update/(?P<pk>\d+)/$', login_required(CategoryEmployeeFieldUpdate.as_view()), name='category_employee_field_update'),
    url(r'^(?P<companies_id>\d+)/cef_delete/(?P<pk>\d+)/$', login_required(CategoryEmployeeFieldDelete.as_view()), name='category_employee_field_delete'),



    # DATA Graph
    url(r'^(?P<pk>\d+)/api/data/$', login_required(get_data), name='api-data'),
    url(r'^(?P<pk>\d+)/api/chart/data/$', login_required(CompanyChartData.as_view())),



    url(r'^(?P<pk>\d+)/dashboard/', login_required(CompanyDashboard.as_view()), name='company_dashboard'),
    url(r'^(?P<pk>\d+)/pending/', login_required(CompanyPending.as_view()), name='company_pending'),

    ###################


]

samson_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from django.conf import settings
from django.conf.urls.static import static
from django.template.backends import django

from apps.company.views import index, CompanyDashboard, RedirectDashboard, CompanyPending

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^404/$', login, {'template_name': '404.html'}, name='error_404'),
                  url(r'^company/', include(('apps.company.urls', 'company'), namespace='company')),
                  url(r'^company_dashboard/',
                      include(('apps.user_profile.urls', 'user_profile'), namespace="company_dashboard")),

                  url(r'^project/', include(('apps.project.urls', 'project'), namespace="project")),

                  url(r'^employee/', include(('apps.employee.urls', 'employee'), namespace="employee")),
                  url(r'^contractor/', include(('apps.contractor.urls','contractor'), namespace="contractor")),
                  url(r'^general_contractor/', include(('apps.general_contractor.urls', 'general_contractor'), namespace="general_contractor")),

                  url(r'^user_profile/', include(('apps.user_profile.urls', 'user_profile'), namespace="user_profile")),

                  url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
                  url(r'^$', login, {'template_name': 'index.html'}, name='login'),
                  # url(r'^dashboard/', DashBoard.as_view(), name='dashboard'),
                  url(r'^logout/', logout_then_login, name='logout'),
                  url(r'^redirect_dashboard/', RedirectDashboard, name='redirect_dashboard'),
                  url(r'^dashboard/', CompanyDashboard, name='company_dashboard'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Necesario por error de Page no found en directorio Media

apps/company/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from apps.company.forms import CompanyForm, CategoryProjectForm, CategoryEmployeeForm, CategoryCostCodeForm, CostCodeForm, CategoryEmployeeFieldForm
from apps.company.models import Company, CategoryProject, CategoryEmployee, CategoryCostCode, CostCode, CategoryEmployeeField
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from apps.project.models import ProjectContractor, ProjectContractorEmployeeField, ProjectMandayStart, ProjectEmployee, ProjectManDaySchedule, DailyProduce, Project
from apps.employee.models import Employee
from apps.contractor.models import EmployeeField

from apps.user_profile.models import UserProfile
# Import Graph
from django.db.models import F, Sum, Avg, Max, Min, Case, When, Value
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import JsonResponse, HttpResponse, request, HttpRequest, HttpResponseRedirect
from django.shortcuts import render


# Create your views here.
# ==============
# COMPANIES
# ==============
class CompanyCreate(CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'apps/company/company_form.html'
    success_url = reverse_lazy('company:company_list')

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        return super(CompanyCreate, self).form_valid(form)

# ========================================
class CompanyList(ListView):
    model = Company
    template_name = 'apps/company/company_list.html'

    def get_context_data(self, **kwargs):
        context = super(CompanyList, self).get_context_data(**kwargs)

        company_list = Company.objects.all()

        context['companyList'] = company_list

        return context


# ========================================
class CompanyUpdate(UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = 'apps/company/company_form.html'
    success_url = reverse_lazy('company:company_list')

    def form_valid(self, form):
        form.instance.update_user = self.request.user
        return super(CompanyUpdate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('company:company_dashboard', kwargs={
                'pk': self.kwargs['pk']
            })
        else:
            return reverse_lazy('company:company_dashboard', args=(self.object.id,))


#######################
## CATEGORY PROJECTS ##
#######################

# LIST
# ============
class CategoryProjectList(ListView):
    model = CategoryProject
    template_name = 'apps/company/category_project/category_project_list.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryProjectList, self).get_context_data(**kwargs)

        category_project_list = CategoryProject.objects.all(). \
            filter(companies_id=self.kwargs['pk'])

        context['CategoryProjectList'] = category_project_list

        return context

# CREATE
# ====================
class CategoryProjectCreate(CreateView):
    model = CategoryProject
    form_class = CategoryProjectForm
    template_name = 'apps/company/category_project/category_project_form.html'
    success_url = reverse_lazy('company:category_project_list')

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        return super(CategoryProjectCreate, self).form_valid(form)

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(CategoryProjectCreate, self).get_initial()

        companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
        initial.update(
            {
                'companies_id': companies_id['id'],
                'companies': companies_id['id']
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(CategoryProjectCreate, self).get_form_kwargs()

        companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
            })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('company:category_project_list', kwargs={'pk': self.kwargs['pk']})
        else:
            return reverse_lazy('company:category_project_list', args=(self.object.id,))

# UPDATE
# =================
class CategoryProjectUpdate(UpdateView):
    model = CategoryProject
    form_class = CategoryProjectForm
    template_name = './apps/company/category_project/category_project_form.html'
    success_url = reverse_lazy('company:category_project_list')

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(CategoryProjectUpdate, self).get_initial()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        initial.update(
            {
                'companies_id': companies_id['id'],
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(CategoryProjectUpdate, self).get_form_kwargs()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
            })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('company:category_project_list', kwargs={'pk': self.kwargs['companies_id']})
        else:
            return reverse_lazy('company:category_project_list', args=(self.object.id,))

# DELETE
# =============
class CategoryProjectDelete(DeleteView):
    model = CategoryProject
    template_name = 'apps/company/category_project/category_project_delete.html'
    success_url = reverse_lazy('company:category_project_list')


    def get_context_data(self, **kwargs):
        context = super(CategoryProjectDelete, self).get_context_data(**kwargs)

        context['DeleteRegisterExist'] = Project.objects.all().filter(companies_id=self.kwargs['companies_id'],category_projects_id=self.kwargs['pk'])

        register_delete = CategoryProject.objects.all().get(companies_id=self.kwargs['companies_id'], pk=self.kwargs['pk'])

        context['DeleteRegister'] = register_delete

        return context

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('company:category_project_list', kwargs={'pk': self.kwargs['companies_id']})
        else:
            return reverse_lazy('company:category_project_list', args=(self.object.id,))


#####################
# CATEGORY EMPLOYEE #
#####################

# LIST
# =======

class CategoryEmployeeList(ListView):
    model = CategoryEmployee
    template_name = 'apps/company/category_employee/category_employee_list.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryEmployeeList, self).get_context_data(**kwargs)

        # Empployee Assigned
        category_employee_list = CategoryEmployee.objects.all(). \
            filter(companies_id=self.kwargs['pk'])

        context['CategoryEmployeeList'] = category_employee_list

        return context

# CREATE
# =========
class CategoryEmployeeCreate(CreateView):
    model = CategoryEmployee
    form_class = CategoryEmployeeForm
    template_name = 'apps/company/category_employee/category_employee_form.html'
    success_url = reverse_lazy('company:category_employee_list')

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        return super(CategoryEmployeeCreate, self).form_valid(form)

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(CategoryEmployeeCreate, self).get_initial()

        if self.kwargs['pk']:
            companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
            initial.update(
                {
                    'companies_id': companies_id['id'],
                    'companies': companies_id['id']
                }
            )
        return initial

    def get_form_kwargs(self):
        kwargs = super(CategoryEmployeeCreate, self).get_form_kwargs()

        if self.kwargs['pk']:
            companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
            kwargs.update(
                {
                    'companies_id': companies_id['id'],
                })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('company:category_employee_list', kwargs={'pk': self.kwargs['pk']})
        else:
            return reverse_lazy('company:category_employee_list', args=(self.object.id,))

# UPDATE
# =========
class CategoryEmployeeUpdate(UpdateView):
    model = CategoryEmployee
    form_class = CategoryEmployeeForm
    template_name = 'apps/company/category_employee/category_employee_form.html'
    success_url = reverse_lazy('company:category_employee_list')

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(CategoryEmployeeUpdate, self).get_initial()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        initial.update(
            {
                'companies_id': companies_id['id'],
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(CategoryEmployeeUpdate, self).get_form_kwargs()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
            })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:

samson_project/templates/apps/company/category_employee_field/category_employee_field_delete.html
{% extends "base/base_site.html" %}
<title>SAMSON Project Management and Comunication - SPMC | {% block title %} Delete of Company {% endblock %}</title>

{% block content %}
    <div class="right_col" role="main">
        <!-- Start Top Title-->
        <div class="col-md-12 col-sm-12 col-xs-12 nav navbar-header product_price">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h2><i class="fa fa-gear"></i> <strong>Category Employee Field<strong class="blue">Delete</strong></strong></h2>

            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 pull-right" align="right">
                <a class="btn btn-warning" href="{%  url 'company:category_employee_field_list' user.userprofile.companies.id  %}">Cancelar</a>

            </div>
        </div>
        <!-- End Top Title-->

        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2 class="green">Category Employee Field Delete | <strong class="green-dark">{{ user.userprofile.companies.name }}</strong></h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <p class="text-muted font-13 m-b-30">
                            <table id="datatable-buttons" class="table table-striped table-bordered">
                                <thead>
                                </thead>
                                {# CODE ELIMINATE#}
                                <form action="" method="post">
                                    {% csrf_token %}
                                    {% if DeleteRegisterExist %}
                                        <h2> <span class="label label-warning">{{ DeleteRegister.name }}</span> It can not be eliminated because there are assigned records.</h2>

                                    {% else %}
                                        <h2>Be sure to eliminate this record <b> <span class="label label-danger">{{ DeleteRegister.name }}</span> ?</b></h2>

                                        <button class="btn btn-danger" type="submit">Yes, Delete</button>
                                        <a class="btn btn-primary" href="{%  url 'company:category_employee_field_list' user.userprofile.companies.id  %}">Cancelar</a>
                                    {% endif %}
                                </form>
                                <tbody>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

samson_project/templates/apps/company/category_employee_field/category_employee_field_form.html
{% extends "base/base_site.html" %}
{% load crispy_forms_tags %}
{% crispy form %}
{% block content %}
    <div class="right_col" role="main">
        <!-- Start Top Title-->
        <div class="col-md-12 col-sm-12 col-xs-12 nav navbar-header product_price">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h2><i class="fa fa-gear"></i> <strong>Category Employee Field</strong></h2>

            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 pull-right" align="right">
                <a class="btn btn-warning" href="{%  url 'company:category_employee_field_list' user.userprofile.companies.id %}">
                    Cancel
                </a>
            </div>
        </div>
        <!-- End Top Title-->

        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><strong>New Category Employee Field</strong></h2>

                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br />

                            {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}
    {{ block.super}}
    <!-- Ion.RangeSlider -->
    <script src="/static/vendors/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>

    <!-- Bootstrap Colorpicker -->
    <script src="/static/vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>

    <!-- jquery.inputmask -->
    <script src="/static/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>

    <!-- jQuery Knob -->
    <script src="/static/vendors/jquery-knob/dist/jquery.knob.min.js"></script>

    <!-- Cropper -->
    <script src="/static/vendors/cropper/dist/cropper.min.js"></script>

    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
{% endblock javascripts %}

samson_project/templates/apps/company/category_employee_field/category_employee_field_list.html
{% extends "base/base_site.html" %}

<title>SAMSON Project Management and Comunication - SPMC | {% block title %} List of companies {% endblock %}</title>


{% block stylesheets %}
    {{ block.super }}
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
        <!-- Start Top Title-->
        <div class="col-md-12 col-sm-12 col-xs-12 nav navbar-header product_price">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h2><i class="fa fa-gear"></i> <strong> Category Employee Field</strong></h2>

            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 pull-right" align="right">
                <a class="btn btn-info" href="{%  url 'company:category_employee_field_create' user.userprofile.companies.id %}">
                    Create
                </a>
            </div>
        </div>
        <!-- End Top Title-->

        <div class="">
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2 class="green"><strong class="green-dark">List of category Employee Field</strong> | {{ user.userprofile.companies.name }}</h2>

                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <table id="datatable-buttons" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Category Employee</th>
                                    {#                                    <th>Status</th>#}
                                    <th>Action</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% if CategoryEmployeeFieldList %}
                                    {% for category_employee in CategoryEmployeeFieldList %}
                                        <tr>
                                            <th scope="row">{{ category_employee.name }}</th>
                                            <td align="center">
                                                <a href="{% url 'company:category_employee_field_update' user.userprofile.companies.id category_employee.id %}" class="btn .btn-transparent btn-xs"><i class="fa fa-pencil fa-lg"></i> </a>
                                                {%  if  user.is_staff and user.userprofile.role is 1  %}
                                                    <a href="{% url 'company:category_employee_field_delete' user.userprofile.companies.id category_employee.id %}" class="btn .btn-transparent btn-xs"><i class="fa fa-trash-o fa-lg"></i> </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}

                                {% else %}
                                    <h4 class="red">We have not yet found information in our database of the selected option.</h4>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>

{% endblock javascripts %}