apps/contractor/urls.py
"""
URLs CONTRACTORS
"""
from django.contrib.auth.decorators import login_required

from django.conf.urls import url
from apps.contractor.views import index, ContractorCreate, ContractorList, ContractorUpdate, ContractorDelete, ContractorDetail, \
    EmployeeFieldList, EmployeeFieldCreate, EmployeeFieldUpdate, \
    ContractorEmployeeFieldCreate, ContractorEmployeeFieldList, ContractorEmployeeFieldAllList, ContractorEmployeeFieldUpdate, ContractorEmployeeFieldAllUpdate,\
    EmployeeFieldProfile,get_data, ContractorChartData


urlpatterns = [
    url(r'^$', index, name='index'),

    url(r'^(?P<pk>\d+)/create/$', \
        login_required(ContractorCreate.as_view()), name='contractor_create'),

    url(r'^(?P<pk>\d+)/list/$', \
        login_required(ContractorList.as_view()), name='contractor_list'),

    url(r'^(?P<companies_id>\d+)/update/(?P<pk>\d+)/$', \
        login_required(ContractorUpdate.as_view()), name='contractor_update'),

    url(r'^(?P<companies_id>\d+)/delete/(?P<pk>\d+)/$', \
        login_required(ContractorDelete.as_view()), name='contractor_delete'),

    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/detail/$', login_required(ContractorDetail.as_view()), name='contractor_detail'),

    # URLs CONTRACTOR EMPLOYEE FIELD
    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/contractor_employee_field_list/$', \
        login_required(ContractorEmployeeFieldList.as_view()), name='contractor_employee_field_list'),

    # all employees
    url(r'^(?P<pk>\d+)/contractor_employee_field_all_list/$', \
        login_required(ContractorEmployeeFieldAllList.as_view()), name='contractor_employee_field_all_list'),

    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/contractor_employee_field_create/(?P<pk>\d+)/$', \
        login_required(ContractorEmployeeFieldCreate.as_view()), name='contractor_employee_field_create'),

    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/contractor_employee_field_update/(?P<pk>\d+)/$', \
        login_required(ContractorEmployeeFieldUpdate.as_view()), name='contractor_employee_field_update'),

    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/contractor_employee_field_all_update/(?P<pk>\d+)/$', \
        login_required(ContractorEmployeeFieldAllUpdate.as_view()), name='contractor_employee_field_all_update'),


    # URLs: EMPLOYEE FIELDs
    url(r'^(?P<companies_id>\d+)/employee_field_create/(?P<pk>\d+)/$', login_required(EmployeeFieldCreate.as_view()), name='employee_field_create'),
    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/employee_field_update/$', login_required(EmployeeFieldUpdate.as_view()),
        name='employee_field_update'),
    url(r'^(?P<pk>\d+)/employee_field_list/$', login_required(EmployeeFieldList.as_view()), name='employee_field_list'),

    # Profile
    url(r'^(?P<companies_id>\d+)/(?P<contractor_id>\d+)/(?P<pk>\d+)/employee_field_profile/$', login_required(EmployeeFieldProfile.as_view()),
        name='contractor_employee_field_profile'),

    # DATA Graph
    url(r'^(?P<pk>\d+)/api/data/$', login_required(get_data), name='api-data'),
    url(r'^(?P<pk>\d+)/api/chart/data/$', login_required(ContractorChartData.as_view())),
    ###################

]

samson_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from django.conf import settings
from django.conf.urls.static import static
from django.template.backends import django

from apps.company.views import index, CompanyDashboard, RedirectDashboard, CompanyPending

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^404/$', login, {'template_name': '404.html'}, name='error_404'),
                  url(r'^company/', include(('apps.company.urls', 'company'), namespace='company')),
                  url(r'^company_dashboard/',
                      include(('apps.user_profile.urls', 'user_profile'), namespace="company_dashboard")),

                  url(r'^project/', include(('apps.project.urls', 'project'), namespace="project")),

                  url(r'^employee/', include(('apps.employee.urls', 'employee'), namespace="employee")),
                  url(r'^contractor/', include(('apps.contractor.urls','contractor'), namespace="contractor")),
                  url(r'^general_contractor/', include(('apps.general_contractor.urls', 'general_contractor'), namespace="general_contractor")),

                  url(r'^user_profile/', include(('apps.user_profile.urls', 'user_profile'), namespace="user_profile")),

                  url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
                  url(r'^$', login, {'template_name': 'index.html'}, name='login'),
                  # url(r'^dashboard/', DashBoard.as_view(), name='dashboard'),
                  url(r'^logout/', logout_then_login, name='logout'),
                  url(r'^redirect_dashboard/', RedirectDashboard, name='redirect_dashboard'),
                  url(r'^dashboard/', CompanyDashboard, name='company_dashboard'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Necesario por error de Page no found en directorio Media

apps/contractor/views.py
from django.shortcuts import render, redirect

from apps.contractor.forms import ContractorForm, EmployeeFieldForm, ContractorEmployeeFieldForm
from apps.contractor.models import Contractor, EmployeeField, ContractorEmployeeField
from apps.project.models import ProjectContractor, DailyProduce, ProjectContractorEmployeeField
from apps.company.models import Company

from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.db.models import F, Q, Sum, Avg, Max, Min, Case, When

# Import Graph
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'base/index.html')

# Create your views here.
# ==================================
# CONTRACTOR CRUD
# ==================================
class ContractorCreate(CreateView):
    model = Contractor
    form_class = ContractorForm
    template_name = 'apps/contractor/contractor_form.html'
    success_url = reverse_lazy('contractor:contractor_list')

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        return super(ContractorCreate, self).form_valid(form)

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(ContractorCreate, self).get_initial()
        companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
        initial.update(
            {
                'companies_id': companies_id['id'],
                'companies': companies_id['id'],
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(ContractorCreate, self).get_form_kwargs()
        companies_id = Company.objects.values('id').get(id=self.kwargs['pk'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
            })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('contractor:contractor_list', kwargs={'pk': self.kwargs['pk']})
        else:
            return reverse_lazy('contractor:contractor_list', args=(self.object.id,))


class ContractorList(ListView):
    model = Contractor
    template_name = 'apps/contractor/contractor_list.html'

    # Pasar parametros a la plantilla usando context
    def get_context_data(self, **kwargs):
        context = super(ContractorList, self).get_context_data(**kwargs)

        context['contractorList'] = Contractor.objects.all().filter(companies_id=self.kwargs['pk'])

        return context


class ContractorUpdate(UpdateView):
    model = Contractor
    form_class = ContractorForm
    template_name = 'apps/contractor/contractor_form.html'
    success_url = reverse_lazy('contractor:contractor_list')

    # Inicializar valores por default en formulario
    def get_initial(self):
        initial = super(ContractorUpdate, self).get_initial()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        initial.update(
            {
                'companies_id': companies_id['id'],
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(ContractorUpdate, self).get_form_kwargs()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
            })

        return kwargs

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('contractor:contractor_list', kwargs={'pk': self.kwargs['companies_id']})
        else:
            return reverse_lazy('contractor:contractor_list', args=(self.object.id,))


class ContractorDelete(DeleteView):
    model = Contractor
    template_name = 'apps/contractor/contractor_delete.html'
    success_url = reverse_lazy('contractor:contractor_list')


    def get_context_data(self, **kwargs):

        context = super(ContractorDelete, self).get_context_data(**kwargs)
        a = ''
        b  = ''
        a = ProjectContractor.objects.filter(contractors_id=self.kwargs['pk']).count()
        b = ContractorEmployeeField.objects.filter(contractors_id=self.kwargs['pk']).count()

        if a > 0:
            context['DeleteRegisterExist'] = a

        if b > 0:
            context['DeleteRegisterExist'] = b

        context['DeleteRegister'] = Contractor.objects.get(companies_id=self.kwargs['companies_id'], pk=self.kwargs['pk'])

        return context

    def get_success_url(self, **kwargs):
        if kwargs != None:
            return reverse_lazy('contractor:contractor_list', kwargs={'pk': self.kwargs['companies_id']})
        else:
            return reverse_lazy('contractor:contractor_list', args=(self.object.id,))


# ###################
# CONTRACTOR DETAIL #
# ###################

class ContractorDetail(DetailView):
    model = Contractor
    template_name = 'apps/contractor/contractor_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ContractorDetail, self).get_context_data(**kwargs)

        ########################################
        # Employee List Assigned to Contractor #
        ########################################
        contractor_employee_field_list = ContractorEmployeeField.objects.select_related('contractors'). \
            all().filter(contractors_id=self.kwargs['pk'])

        context['ContractorEmployeeFieldList'] = contractor_employee_field_list

        ########################################
        # Employee List Assigned to Contractor #
        ########################################
        project_contractor_list = ProjectContractor.objects.select_related('contractors'). \
            all().filter(contractors_id=self.kwargs['pk'])

        context['ProjectContractorList'] = project_contractor_list

        total_projects = 0
        total_man_days = 0
        total_production_exp = 0
        total_produccion_exe = 0
        total_employees = 0
        total_hours = 0
        total_cost_man_days_spend = 0

        # { MAN DAYS CALCULATOR
        total_projects = ProjectContractor.objects.all().filter(contractors_id=self.kwargs['pk']).count()
        total_employees_field = ContractorEmployeeField.objects.all().filter(contractors_id=self.kwargs['pk']).count()

        contractor_cost_hours = DailyProduce.objects. \
            values('project_contractor_employees_field__project_contractors__contractors__companies__name'). \
            filter(project_contractor_employees_field__project_contractors__contractors__id=self.kwargs['pk']). \
            annotate(
            cost=Sum(
                Case(
                    When(project_manday_schedules__projects__is_wage_scale=False,
                         then=F('work_hours') * F('project_manday_schedules__regular_cost')
                         ),
                    When(project_manday_schedules__projects__is_wage_scale=True,
                         then=F('work_hours') * F('project_manday_schedules__wage_cost')
                         )
                )
            ),
            cost_md=Sum(
                Case(
                    When(project_manday_schedules__projects__is_wage_scale=False,
                         then=F('work_hours') * F('project_manday_schedules__regular_cost')
                         ),
                    When(project_manday_schedules__projects__is_wage_scale=True,
                         then=F('work_hours') * F('project_manday_schedules__wage_cost')
                         )
                )
            ),
            hours=Sum('work_hours')
        )

        if contractor_cost_hours.count() > 0:
            if contractor_cost_hours[0]['cost'] is not None and contractor_cost_hours[0]['hours'] is not None:
                total_cost_man_days_spend = contractor_cost_hours[0]['cost']
                total_hours = contractor_cost_hours[0]['hours'] + 0

        data = ({
            'total_projects': total_projects,
            'total_man_days': total_hours / 8,
            'total_cost_man_days_spend': total_cost_man_days_spend,
            'total_produccion_exe': total_produccion_exe,
            'total_employees_field': total_employees_field
        })
        context['ContractorDetail'] = data

        return context

#############################
# CONTRACTOR EMPLOYEE FIELD #
#############################

class ContractorEmployeeFieldCreate(CreateView):
    model = ContractorEmployeeField
    form_class = ContractorEmployeeFieldForm
    template_name = 'apps/contractor/contractor_employee_field/contractor_employee_field_form.html'

    def form_valid(self, form):
        form.instance.create_user = self.request.user
        form.save(commit=False)  # Para obtener el ID
        EmployeeField.objects.filter(id=form.instance.employees_field_id).update(is_assigned=True)

        form.save()  # Guardamos el codigo

        return super(ContractorEmployeeFieldCreate, self).form_valid(form)

    def get_initial(self):
        initial = super(ContractorEmployeeFieldCreate, self).get_initial()

        initial.update(
            {
                'companies':self.kwargs['companies_id'],
                'contractors': self.kwargs['contractor_id'],
                'contractor_id': self.kwargs['contractor_id'],
                'employees_field': self.kwargs['pk']
            }
        )

        return initial

    def get_form_kwargs(self):
        kwargs = super(ContractorEmployeeFieldCreate, self).get_form_kwargs()

        companies_id = Company.objects.values('id').get(id=self.kwargs['companies_id'])
        kwargs.update(
            {
                'companies_id': companies_id['id'],
                'contractor_id': self.kwargs['contractor_id'],
                'employees_field_id': self.kwargs['pk'],
            })

samson_project/templates/apps/contractor/contractor_delete.html
{% extends "base/base_site.html" %}
<title>SAMSON Project Management and Comunication - SPMC | {% block title %} Delete of Company {% endblock %}</title>

{% block content %}
    <div class="right_col" role="main">
        <!-- Start Top Title-->
        <div class="col-md-12 col-sm-12 col-xs-12 nav navbar-header product_price">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h2><i class="fa fa-gear"></i> <strong>Contractor <strong class="blue">Delete</strong></strong></h2>

            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 pull-right" align="right">
                <a class="btn btn-warning" href="{%  url 'contractor:contractor_list' user.userprofile.companies.id  %}">Cancelar</a>

            </div>
        </div>
        <!-- End Top Title-->

        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2 class="green">Contractor | <strong class="green-dark">{{ user.userprofile.companies.name }}</strong></h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <p class="text-muted font-13 m-b-30">
                            <table id="datatable-buttons" class="table table-striped table-bordered">
                                <thead>
                                </thead>
                                {# CODE ELIMINATE#}
                                <form action="" method="post">
                                    {% csrf_token %}
                                    {% if DeleteRegisterExist %}
                                        <h2> <span class="label label-warning">{{ DeleteRegister }}</span> It can not be eliminated because there are assigned records.</h2>

                                    {% else %}
                                        <h2>Be sure to eliminate this record <b> <span class="label label-danger">{{ DeleteRegister }}</span> ?</b></h2>

                                        <button class="btn btn-danger" type="submit">Yes, Delete</button>
                                        <a class="btn btn-primary" href="{%  url 'contractor:contractor_list' user.userprofile.companies.id  %}">Cancelar</a>
                                    {% endif %}
                                </form>
                                <tbody>
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

samson_project/templates/apps/contractor/contractor_form.html
{% extends "base/base_site.html" %}
{% load crispy_forms_tags %}
{% crispy form %}

<title>SAMSON Project Management and Comunication - SPMC | {% block title %} Create/Update Contractor {% endblock %}</title>

{% block content %}
    <div class="right_col" role="main">
        <!-- Start Top Title-->
        <div class="col-md-12 col-sm-12 col-xs-12 nav navbar-header product_price">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h2><i class="fa fa-gear"></i> <strong>New Contractor</strong></h2>

            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 pull-right" align="right">
                <a class="btn btn-warning" href="{%  url 'contractor:contractor_list' user.userprofile.companies.id %}">
                    Cancel
                </a>
            </div>
        </div>
        <!-- End Top Title-->

        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><strong>New Contractor</strong><small></small></h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br />
                            {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}
    {{ block.super}}
    <!-- Ion.RangeSlider -->
    <script src="/static/vendors/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>

    <!-- Bootstrap Colorpicker -->
    <script src="/static/vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>

    <!-- jquery.inputmask -->
    <script src="/static/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>

    <!-- jQuery Knob -->
    <script src="/static/vendors/jquery-knob/dist/jquery.knob.min.js"></script>

    <!-- Cropper -->
    <script src="/static/vendors/cropper/dist/cropper.min.js"></script>

    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
{% endblock javascripts %}

samson_project/templates/apps/contractor/contractor_list.html
{% extends "base/base_site.html" %}
<title>SAMSON Project Management and Comunication - SPMC | {% block title %} List of Contractor {% endblock %}</title>

{% block stylesheets %}
    {{ block.super }}
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
        <!-- Start Top Title-->
        <div class="col-md-12 col-sm-12 col-xs-12 nav navbar-header product_price">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <h2><i class="fa fa-road"></i> <strong> Database of Contractors</strong></h2>

            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 pull-right" align="right">
                <a class="btn btn-info" href="{%  url 'contractor:contractor_create' user.userprofile.companies.id %}">
                    Create
                </a>
            </div>
        </div>
        <!-- End Top Title-->

        <div class="">
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h3 align="center" class="green">List of Contractors | <strong class="green-dark">{{ user.userprofile.companies.name }}</strong></h3>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <p class="text-muted font-13 m-b-30">
                            </p>
                            <table style="border-bottom-right-radius: unset" id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                <thead >
                                <tr>
                                    <th>Contractor Name</th>
                                    <th>CEO</th>
                                    <th>President</th>
                                    <th>Contact Information</th>
                                    <th># Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if contractorList %}
                                    {% for contractor in contractorList %}
                                        <tr>
                                            <td scope="row">
                                                <strong>{{ contractor.name }} </strong></br>
                                                <small class="green">{{ contractor.street_address }}, {{ contractor.city_address }}, {{ contractor.state_address }}</small>
                                            </td>
                                            <td>{{ contractor.ceo }}</td>
                                            <td>{{ contractor.president }}</td>

                                            <td>
                                                {{ contractor.phone_number }},  Ext. {{ contractor.phone_number_ext }} </br>
                                                <small class="blue">{{ contractor.email }}</small>

                                            </td>
                                            <td>
                                                {%  if  user.is_staff and user.userprofile.role is 1 %}
                                                    <a href="{% url 'contractor:contractor_update' user.userprofile.companies.id contractor.id %}" class="btn .btn-transparent btn-sm"><i class="fa fa-pencil fa-lg"></i></a>
                                                    <a href="{% url 'contractor:contractor_delete' user.userprofile.companies.id contractor.id %}" class="btn .btn-transparent btn-sm"><i class="fa fa-trash-o fa-lg"></i></a>
                                                {% endif %}
                                                <a href="{%  url 'contractor:contractor_detail' user.userprofile.companies.id contractor.id %}" class="btn .btn-transparent  btn-xs"><i class="fa fa-eye fa-lg"></i> </a>

                                            </td>
                                        </tr>
                                    {% endfor %}

                                {% else %}
                                    <h4 class="red">We have not yet found information in our database of the selected option.</h4>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>

{% endblock javascripts %}

samson_project/templates/apps/contractor/index.html
{% extends 'base/base.html' %}