apps/company/urls.py
"""
URLs Company
"""
from django.contrib.auth.decorators import login_required

from django.conf.urls import url
from apps.company.views import index, CompanyCreate, CompanyList, CompanyUpdate,  \
    CategoryProjectCreate, CategoryProjectList, CategoryProjectDelete, CategoryProjectUpdate, \
    CategoryEmployeeCreate, CategoryEmployeeList, CategoryEmployeeDelete, CategoryEmployeeUpdate, \
    CategoryCostCodeCreate, CategoryCostCodeList, CategoryCostCodeDelete, CategoryCostCodeUpdate,\
    CostCodeCreate, CostCodeList, CostCodeDelete, CostCodeUpdate, \
    CategoryEmployeeFieldCreate, CategoryEmployeeFieldList, CategoryEmployeeFieldDelete, CategoryEmployeeFieldUpdate, CompanyChartData, get_data, CompanyDashboard, CompanyPending

urlpatterns = [
    url(r'^$', index, name='index'),
    # URLs: Company
    url(r'^create$', login_required(CompanyCreate.as_view()), name='company_create'),
    url(r'^list$', login_required(CompanyList.as_view()), name='company_list'),
    url(r'^update/(?P<pk>\d+)/$', login_required(CompanyUpdate.as_view()), name='company_update'),
    #url(r'^delete/(?P<pk>\d+)/$', login_required(CompanyDelete.as_view()), name='company_delete'),


    # URLs: Category Project
    url(r'^(?P<pk>\d+)/cp_create/$', login_required(CategoryProjectCreate.as_view()), name='category_project_create'),
    url(r'^(?P<pk>\d+)/cp_list/$', login_required(CategoryProjectList.as_view()), name='category_project_list'),
    url(r'^(?P<companies_id>\d+)/cp_update/(?P<pk>\d+)/$', login_required(CategoryProjectUpdate.as_view()), name='category_project_update'),
    url(r'^(?P<companies_id>\d+)/cp_delete/(?P<pk>\d+)/$', login_required(CategoryProjectDelete.as_view()), name='category_project_delete'),


    # URLs: Category Employee
    url(r'^(?P<pk>\d+)/ce_create/$', login_required(CategoryEmployeeCreate.as_view()), name='category_employee_create'),
    url(r'^(?P<pk>\d+)/ce_list/$', login_required(CategoryEmployeeList.as_view()), name='category_employee_list'),
    url(r'^(?P<companies_id>\d+)/ce_update/(?P<pk>\d+)/$', login_required(CategoryEmployeeUpdate.as_view()), name='category_employee_update'),
    url(r'^(?P<companies_id>\d+)/ce_delete/(?P<pk>\d+)/$', login_required(CategoryEmployeeDelete.as_view()), name='category_employee_delete'),


    # URLs: Category Cost code
    url(r'^(?P<pk>\d+)/ccc_create/$', login_required(CategoryCostCodeCreate.as_view()), name='category_cost_code_create'),
    url(r'^(?P<pk>\d+)/ccc_list/$', login_required(CategoryCostCodeList.as_view()), name='category_cost_code_list'),
    url(r'^(?P<companies_id>\d+)/ccc_update/(?P<pk>\d+)/$', login_required(CategoryCostCodeUpdate.as_view()), name='category_cost_code_update'),
    url(r'^(?P<companies_id>\d+)/ccc_delete/(?P<pk>\d+)/$', login_required(CategoryCostCodeDelete.as_view()), name='category_cost_code_delete'),


    # URLs: Cost code
    url(r'^(?P<pk>\d+)/cc_create/$', login_required(CostCodeCreate.as_view()), name='cost_code_create'),
    url(r'^(?P<pk>\d+)/cc_list/$', login_required(CostCodeList.as_view()), name='cost_code_list'),
    url(r'^(?P<companies_id>\d+)/cc_update/(?P<pk>\d+)/$', login_required(CostCodeUpdate.as_view()), name='cost_code_update'),
    url(r'^(?P<companies_id>\d+)/cc_delete/(?P<pk>\d+)/$', login_required(CostCodeDelete.as_view()), name='cost_code_delete'),


    # URLs: Category Employee Field
    url(r'^(?P<pk>\d+)/cef_create/$', login_required(CategoryEmployeeFieldCreate.as_view()), name='category_employee_field_create'),
    url(r'^(?P<pk>\d+)/cef_list/$', login_required(CategoryEmployeeFieldList.as_view()), name='category_employee_field_list'),
    url(r'^(?P<companies_id>\d+)/cef_update/(?P<pk>\d+)/$', login_required(CategoryEmployeeFieldUpdate.as_view()), name='category_employee_field_update'),
    url(r'^(?P<companies_id>\d+)/cef_delete/(?P<pk>\d+)/$', login_required(CategoryEmployeeFieldDelete.as_view()), name='category_employee_field_delete'),



    # DATA Graph
    url(r'^(?P<pk>\d+)/api/data/$', login_required(get_data), name='api-data'),
    url(r'^(?P<pk>\d+)/api/chart/data/$', login_required(CompanyChartData.as_view())),



    url(r'^(?P<pk>\d+)/dashboard/', login_required(CompanyDashboard.as_view()), name='company_dashboard'),
    url(r'^(?P<pk>\d+)/pending/', login_required(CompanyPending.as_view()), name='company_pending'),

    ###################


]

apps/project/urls.py
"""
URLs Project
"""
from django.contrib.auth.decorators import login_required

from django.conf.urls import url

from apps.project.views import ProjectCreate, ProjectDelete, ProjectList, ProjectUpdate, ProjectDetail, \
    ProjectDailyProduceCreate, ProjectEmployeeList, ProjectEmployeeCreate, ProjectEmployeeDelete, ProjectEmployeeUpdate, \
    ProjectContractorList, ProjectContractorCreate, ProjectContractorDelete, ProjectContractorUpdate, \
    ProjectManDayScheduleList, ProjectManDayScheduleCreate, ProjectManDayScheduleUpdate, ProjectManDayScheduleDelete, \
    ProjectContractorEmployeeFieldList, ProjectContractorEmployeeFieldCreate, \
    ProjectContractorEmployeeFieldUpdate,ProjectContractorEmployeeFieldDailyProduceList, \
    ProjectFloorPhaseList, ProjectFloorPhaseCreate, ProjectFloorPhaseAreaCreate, ProjectFloorPhaseUpdate, get_data, GeneratePdf, ChartData, HomeView, ReportePersonasPDF, \
    ProjectManDayScheduleReport, ProjectManDayScheduleLaborReport, ProjectDailyProduceUpdate, ProjectActivityLaborReport, ProjectDailyProduceDelete, ProjectAssignToUserList

urlpatterns = [
    ###############
    # URLs PROJECT
    ###############

    url(r'^(?P<pk>\d+)/create/(?P<user_id>\d+)/$',
        login_required(ProjectCreate.as_view()), name='project_create'),

    url(r'^(?P<companies_id>\d+)/list/(?P<user_id>\d+)/$',
        login_required(ProjectList.as_view()), name='project_list'),

    url(r'^(?P<companies_id>\d+)/update/(?P<pk>\d+)/(?P<user_id>\d+)/$',
        login_required(ProjectUpdate.as_view()), name='project_update'),

    url(r'^delete/(?P<pk>\d+)/$',
        login_required(ProjectDelete.as_view()), name='project_delete'),

    url(r'^(?P<pk>\d+)/detail/date/$', login_required(ProjectDetail.as_view()), name='project_detail'),


    # DATA Graph
    url(r'^home/$', HomeView.as_view(), name='home'),
    url(r'^(?P<pk>\d+)/api/data/$', login_required(get_data), name='api-data'),
    url(
        r'^(?P<pk>\d+)/api/chart/data/(?P<years>[0-9]{4})-(?P<months>[0-9]{2})-(?P<days>[0-9]{2})/(?P<yeare>[0-9]{4})-(?P<monthe>[0-9]{2})-(?P<daye>[0-9]{2})/$',
        login_required(ChartData.as_view())),

    # PROJECT REPORTS
    url(r'^(?P<companies_id>\d+)/detail/(?P<pk>\d+)/date/$', login_required(GeneratePdf.as_view()), name='project_contractors_report'),

    url(r'^(?P<companies_id>\d+)/detail/(?P<pk>\d+)/r/$', login_required(ReportePersonasPDF.as_view()),
        name='project_personas_report'),

    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/report/$', login_required(ProjectManDayScheduleReport.as_view()),
        name='project_manday_schedule_report'),

    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/man_days_floor_rpt/$', login_required(ProjectManDayScheduleLaborReport.as_view()),
        name='project_manday_schedule_labor_report'),

    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/activity_labor_rpt/$',
        login_required(ProjectActivityLaborReport.as_view()),
        name='project_activity_labor_report'),

    url(r'^rp_pdf/$',login_required(ReportePersonasPDF.as_view()), name="reporte_personas_pdf"),

    ##############################
    # URLs PROJECT DAILY PRODUCED
    ##############################
    # CREATE
    url(r'^project_daily_produced_create/(?P<pk>\d+)/$',
        login_required(ProjectDailyProduceCreate.as_view()), name='project_daily_produced_create'),

    # DELETE
    url(r'^(?P<project_id>\d+)/project_daily_produced_delete/(?P<pk>\d+)/$',
        login_required(ProjectDailyProduceDelete.as_view()), name='project_daily_produced_delete'),

    # UPDATE
    url(r'^(?P<project_id>\d+)/(?P<project_contractor_employees_field_id>\d+)/(?P<project_manday_schedules_id>\d+)/project_daily_produced_update/(?P<pk>\d+)/$',
        login_required(ProjectDailyProduceUpdate.as_view()), name='project_daily_produced_update'),

    url(r'^(?P<pk>\d+)/project_contractor_employee_field_daily_produce_list/(?P<contractors_id>\d+)/$',
        login_required(ProjectContractorEmployeeFieldDailyProduceList.as_view()),
        name='project_contractor_employee_field_daily_produce_list'),


    # ########################### #
    # URLs PROJECT TEAM MEMBERS   #
    # ########################### #

    url(r'^(?P<companies_id>\d+)/project_employee_list/(?P<pk>\d+)/$',
        login_required(ProjectEmployeeList.as_view()), name='project_employee_list'),

    url(r'^(?P<companies_id>\d+)/(?P<project_id>\d+)/project_employee_create/(?P<pk>\d+)/$',
        login_required(ProjectEmployeeCreate.as_view()), name='project_employee_create'),

    url(r'^(?P<companies_id>\d+)/(?P<project_id>\d+)/project_employee_update/(?P<pk>\d+)/$',
        login_required(ProjectEmployeeUpdate.as_view()), name='project_employee_update'),

    url(r'^(?P<project_id>\d+)/(?P<pk>\d+)/project_employee_delete/$',
        login_required(ProjectEmployeeDelete.as_view()), name='project_employee_delete'),

    # ########################### #
    # URLs ASSIGN PROJECT TO USER #
    # ########################### #

    url(r'^(?P<companies_id>\d+)/project_assign_project_to_user_list/$',
        login_required(ProjectAssignToUserList.as_view()), name='project_assign_project_to_user_list'),

    ##############################
    # URLs PROJECT CONTRACTOR
    ##############################
    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/project_contractor_list/$',
        login_required(ProjectContractorList.as_view()), name='project_contractor_list'),

    url(r'^(?P<companies_id>\d+)/(?P<project_id>\d+)/project_contractor_create/(?P<pk>\d+)/$',
        login_required(ProjectContractorCreate.as_view()), name='project_contractor_create'),

    url(r'^(?P<companies_id>\d+)/(?P<project_id>\d+)/project_contractor_update/(?P<pk>\d+)/$',
        login_required(ProjectContractorUpdate.as_view()), name='project_contractor_update'),

    url(r'^(?P<project_id>\d+)/project_contractor_delete/(?P<pk>\d+)/$',
        login_required(ProjectContractorDelete.as_view()), name='project_contractor_delete'),

    #################################
    # URLs PROJECT MAN DAYS SCHEDULE
    #################################

    url(r'^(?P<companies_id>\d+)/(?P<pk>\d+)/project_manday_schedule_list/$',
        login_required(ProjectManDayScheduleList.as_view()), name='project_manday_schedule_list'),

    url(r'^(?P<companies_id>\d+)/(?P<project_id>\d+)/project_manday_schedule_create/(?P<pk>\d+)/$',
        login_required(ProjectManDayScheduleCreate.as_view()), name='project_manday_schedule_create'),

    url(r'^(?P<companies_id>\d+)/(?P<project_id>\d+)/project_manday_schedule_update/(?P<pk>\d+)/$',
        login_required(ProjectManDayScheduleUpdate.as_view()), name='project_manday_schedule_update'),

    url(r'^(?P<project_id>\d+)/project_manday_schedule_delete/(?P<pk>\d+)/$',
        login_required(ProjectManDayScheduleDelete.as_view()), name='project_manday_schedule_delete'),

    ##########################
    # URLs PROJECT FLOOR PHASE
    ##########################

    url(r'^(?P<companies_id>\d+)/project_floor_phase_list/(?P<pk>\d+)/$',
        login_required(ProjectFloorPhaseList.as_view()), name='project_floor_phase_list'),

    url(r'^(?P<companies_id>\d+)/project_floor_phase_create/(?P<pk>\d+)/$',
        login_required(ProjectFloorPhaseCreate.as_view()), name='project_floor_phase_create'),

    url(r'^(?P<companies_id>\d+)/(?P<project_id>\d+)/project_floor_phase_update/(?P<pk>\d+)/$',
        login_required(ProjectFloorPhaseUpdate.as_view()), name='project_floor_phase_update'),

    ##########################
    # URLs PROJECT FLOOR AREA
    ##########################
    url(r'^(?P<pk>\d+)/project_floor_phase_area_create/$',
        login_required(ProjectFloorPhaseAreaCreate.as_view()), name='project_floor_phase_area_create'),

    #########################################
    # URLs PROJECT CONTRACTOR EMPLOYEE FIELD
    #########################################

    url(r'^(?P<pk>\d+)/project_contractor_employee_field_list/(?P<contractors_id>\d+)/$',
        login_required(ProjectContractorEmployeeFieldList.as_view()), name='project_contractor_employee_field_list'),

    url(r'^(?P<project_contractor_id>\d+)/project_contractor_employee_field_create/(?P<contractor_id>\d+)/(?P<pk>\d+)/$',
        login_required(ProjectContractorEmployeeFieldCreate.as_view()), name='project_contractor_employee_field_create'),

    url(r'^(?P<project_contractor_id>\d+)/project_contractor_employee_field_update/(?P<pk>\d+)/$',
        login_required(ProjectContractorEmployeeFieldUpdate.as_view()), name='project_contractor_employee_field_update'),

]

samson_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

from django.conf import settings
from django.conf.urls.static import static
from django.template.backends import django

from apps.company.views import index, CompanyDashboard, RedirectDashboard, CompanyPending

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^404/$', login, {'template_name': '404.html'}, name='error_404'),
                  url(r'^company/', include(('apps.company.urls', 'company'), namespace='company')),
                  url(r'^company_dashboard/',
                      include(('apps.user_profile.urls', 'user_profile'), namespace="company_dashboard")),

                  url(r'^project/', include(('apps.project.urls', 'project'), namespace="project")),

                  url(r'^employee/', include(('apps.employee.urls', 'employee'), namespace="employee")),
                  url(r'^contractor/', include(('apps.contractor.urls','contractor'), namespace="contractor")),
                  url(r'^general_contractor/', include(('apps.general_contractor.urls', 'general_contractor'), namespace="general_contractor")),

                  url(r'^user_profile/', include(('apps.user_profile.urls', 'user_profile'), namespace="user_profile")),

                  url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
                  url(r'^$', login, {'template_name': 'index.html'}, name='login'),
                  # url(r'^dashboard/', DashBoard.as_view(), name='dashboard'),
                  url(r'^logout/', logout_then_login, name='logout'),
                  url(r'^redirect_dashboard/', RedirectDashboard, name='redirect_dashboard'),
                  url(r'^dashboard/', CompanyDashboard, name='company_dashboard'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Necesario por error de Page no found en directorio Media

samson_project/templates/apps/project/project_manday_schedule/project_mds_delete.html
{% extends "base/base_site.html" %}

<title>SAMSON Project Management and Comunication - SPMC | {% block title %} Delete of Company {% endblock %}</title>

{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Company module: Delete Cost Code</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Category Cost Code <small>(Elimination of Category Cost Code)</small></h2>

                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <p class="text-muted font-13 m-b-30">
                                Make sure there is no information related to the company <button class="btn btn-warning">{{ object.name }}</button>, since all the information will be lost without being able to recover.</p>
                            <table id="datatable-buttons" class="table table-striped table-bordered">
                                <thead>
                                </thead>
                                {# CODE ELIMINATE#}
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <h3>Be sure to eliminate Category Cost Code <b>{{ object.name}} ?</b></h3>

                                    <button class="btn btn-danger" type="submit">Yes, Delete</button>
                                    <a class="btn btn-primary" href="{%  url 'company:category_employee_list' %}">Cancelar</a>

                                </form>

                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

samson_project/templates/apps/project/project_manday_schedule/project_mds_form.html
{% extends "base/base_site.html" %}
{#{% load widget_tweaks %}#}
{% load crispy_forms_tags %}
{% crispy form %}
{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <!-- Start Top Title-->
            <div class="col-md-12 col-sm-12 col-xs-12 nav navbar-header product_price">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <h2> <strong> Assign <strong class="blue">Man Day Schedule</strong> to Project</strong></h2>

                </div>
                <div class="col-md-6 col-sm-6 col-xs-12 pull-right" align="right">
                    <a class="btn btn-warning"  href="{% url 'project:project_detail' project_info.id %}">
                        <i class="fa fa-reply"></i> Return to Projects
                    </a>
                </div>
            </div>
            <!-- End Top Title-->
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h3><strong> <i class="fa fa-building-o fa-lg"></i> {{ project_info.name }}</strong></h3>

                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br />
                            {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}
    {{ block.super}}
    <!-- Ion.RangeSlider -->
    <script src="/static/vendors/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>

    <!-- Bootstrap Colorpicker -->
    <script src="/static/vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>

    <!-- jquery.inputmask -->
    <script src="/static/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>

    <!-- jQuery Knob -->
    <script src="/static/vendors/jquery-knob/dist/jquery.knob.min.js"></script>

    <!-- Cropper -->
    <script src="/static/vendors/cropper/dist/cropper.min.js"></script>

    <!-- validator -->
    <script src="/static/vendors/validator/validator.js"></script>
{% endblock javascripts %}

samson_project/templates/apps/project/project_manday_schedule/project_mds_form2.html
{% extends "base/base_site.html" %}
{% load crispy_forms_tags %}
{% crispy form %}
{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Company module: Category Employee</h3>
                </div>
                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">

                            <button class="btn btn-default" type="button">Go!</button>
                            <span class="input-group-btn">
                             <a class="btn btn-warning" href="{%  url 'company:cost_code_list' %}">
                                 Cancel
                             </a>
                             </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2><strong>New Category Employee</strong><small>different form elements</small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a>
                                        </li>
                                        <li><a href="#">Settings 2</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a class="close-link" href=""><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br />

                                {% crispy form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- Ion.RangeSlider -->
  <script src="/static/vendors/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>

  <!-- Bootstrap Colorpicker -->
  <script src="/static/vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>

    <!-- jquery.inputmask -->
  <script src="/static/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>

  <!-- jQuery Knob -->
  <script src="/static/vendors/jquery-knob/dist/jquery.knob.min.js"></script>

    <!-- Cropper -->
  <script src="/static/vendors/cropper/dist/cropper.min.js"></script>

  <!-- validator -->
  <script src="/static/vendors/validator/validator.js"></script>
{% endblock javascripts %}

samson_project/templates/apps/project/project_manday_schedule/project_mds_list-no.html
{% extends "base/base_site.html" %}

<title>SAMSON Project Management and Comunication - SPMC | {% block title %} List of companies {% endblock %}</title>
{% block stylesheets %}
    {{ block.super }}
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Company module: Cost Code</h3>
                </div>


                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">

{#                            <button class="btn btn-default" type="button">Go!</button>#}
                            <span class="input-group-btn">
                             <a class="btn btn-info" href="{%  url 'company:cost_code_create' %}">
                                 Create
                             </a>
                             </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>List of cost code<small>(List of registered of category project)</small></h2>

                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <p class="text-muted font-13 m-b-30">
                                The Buttons extension for DataTables provides a common set of options, API methods and styling to display buttons on a page that will interact with a DataTable. The core library provides the based framework upon which plug-ins can built.
                            </p>
                            <table id="datatable-buttons" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Category</th>
                                    <th>Cost code</th>
                                    <th>Unit</th>
                                    <th>Code labor</th>
                                    <th>Code Material</th>

                                    <th>Production</th>
                                    <th>Status</th>
                                    <th>Action</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% if object_list %}
                                    {% for cost_code in object_list %}
                                        <tr>
                                            <th scope="row">{{ cost_code.category_cost_codes }}</th>
                                            <td>{{ cost_code.name }}</td>
                                            <td>{{ cost_code.unit }}</td>

                                            <td>{{ cost_code.code_labor }}</td>
                                            <td>{{ cost_code.code_material }}</td>

                                            <td>{{ cost_code.production }}</td>

                                            <td>{{ cost_code.is_active }}</td>
                                            <td align="center">
                                                  <a href="{% url 'company:cost_code_update' cost_code.id %}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                                  <a href="{% url 'company:cost_code_delete' cost_code.id %}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>

                                            </td>
                                            {% comment %}
                                            <td>
                                             </td>
                                            {% endcomment %}
                                        </tr>
                                    {% endfor %}

                                {% else %}
                                    <h4 class="red">We have not yet found information in our database of the selected option.</h4>
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>

{% endblock javascripts %}